name: default
channels:
- conda-forge
- nodefaults
dependencies:
- python 3.10.*
- python >=3.10
- pip
- pip:
  - eradiate[kernel]==0.31.1.dev0
  - ipykernel
  - ipywidgets
  - seaborn
  - jupyterlab
  - jupyter-ruff>=0.3.0, <0.4
