[project]
authors = [{name = "Vincent Leroy", email = "vincent.leroy@rayference.eu"}]
dependencies = [
    "eradiate[kernel]==0.30.0",
    "ipykernel",
    "ipywidgets",
    "seaborn",
]
name = "paper-eradiate-v100"
requires-python = ">= 3.10"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
paper_eradiate_v100 = { path = ".", editable = true }

[tool.pixi.feature.py310]
dependencies = { python = "3.10.*"}

[tool.pixi.environments.default]
features = ["py310"]

[tool.pixi.tasks]
